[package]
name = "omnichat"
version = "0.0.0"
authors = ["Ben Kimock <kimockb@gmail.com>"]

[dependencies]
failure = "0.1.1"
termion = "1.5.1"
slack_api = {path = "/home/ben/slack-rs-api"}
websocket = "0.20.2"
serde_json = "1.0.9"

