[package]
name = "omnichat"
version = "0.0.0"
authors = ["Ben Kimock <kimockb@gmail.com>"]

[dependencies]
inlinable_string = "0.1"
failure = "0.1"
websocket = "0.20"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
toml = "0.4"
lazy_static = "1.0"
regex = "1.0"
futures = "0.1"
openssl-probe = "0.1"
chrono = "0.4"
log = {version="0.4", features=["std"]}
termion = "1.5"
libc = "0.2"
signal-hook = "0.1"
textwrap = "0.10"
dirs = "1.0"
slack = {path = "slack"}
openssl = { version = "0.10", features = ["vendored"] }
tokio-core = "0.1"
tokio = "0.1"
hyper = "0.12"
hyper-rustls = "0.14"
serde_urlencoded = "0.5"
hyper-tls = "0.3"

