[package]
name = "omnichat"
version = "0.0.0"
authors = ["Ben Kimock <kimockb@gmail.com>"]

[dependencies]
failure = "0.1"
termion = "1.5"
websocket = "0.20"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
toml = "0.4"
lazy_static = "1.0"
textwrap = "0.9"
slack_api = {git = "https://github.com/saethlin/slack-rs-api"}
discord = {git = "https://github.com/tinaun/discord-rs", branch="async_internals"}

[profile.release]
