[package]
name = "omnichat"
version = "0.0.0"
authors = ["Ben Kimock <kimockb@gmail.com>"]

[dependencies]
derive_more = "0.10"
failure = "0.1"
termion = "1.5"
websocket = "0.20"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
toml = "0.4"
lazy_static = "1.0"
textwrap = "0.9"
spmc = "0.2"
regex = "0.2"
backoff = "0.1"
irc = "0.13"
futures = "0.1"
openssl-probe = "0.1"
chrono = "0.4"
chan-signal = "0.3"
#slack_api = {path = "/home/ben/slack-rs-api"}
slack_api = {git = "https://github.com/saethlin/slack-rs-api", branch="types"}
discord = {git = "https://github.com/tinaun/discord-rs", branch="async_internals"}
