[package]
name = "omnichat"
version = "0.0.0"
authors = ["Ben Kimock <kimockb@gmail.com>"]

[dependencies]
inlinable_string = "0.1"
failure = "0.1"
websocket = "0.20"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
toml = "0.4"
lazy_static = "1.0"
spmc = "0.2"
regex = "1.0"
backoff = "0.1"
futures = "0.1"
openssl-probe = "0.1"
chrono = "0.4"
reqwest = "0.9"
log = {version="0.4", features=["std"]}
termion = "1.5"
libc = "0.2"
signal-hook = "0.1"
textwrap = "0.10"
dirs = "1.0"
slack_api = {git = "https://github.com/saethlin/slack-rs-api", branch="types", features=["reqwest_support", "chrono"]}
openssl = { version = "0.10", features = ["vendored"] }
tokio-core = "0.1"

[profile.release]
lto = true
