[package]
name = "ynit"
version = "0.1.0"
authors = ["Ben Kimock <kimockb@gmail.com>"]

[dependencies]
failure = "0.1.1"
termion = "1.5.1"
slack_api = "0.19.0"
websocket = "0.20.2"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"

