version: 2

jobs:  
  build:
    docker:
      - image: saethlin/omnichat:latest

    environment:
      # Set your codecov token if your repository is private.
      TZ: "/usr/share/zoneinfo/America/New_York"

    steps:
      - checkout
      - restore_cache:
          key: project-cache-{{ checksum "Cargo.lock" }}
      - run:
          name: Stable Build
          command: cargo build
      - run:
          name: Test
          command: cargo test
      - save_cache:
          key: project-cache-{{ checksum "Cargo.lock" }}
          paths:
            - "target"
            - "~/.cargo"

